#!/bin/sh 

choice=$(printf " Package Manager\n Settings\n󰋩 Randow Wallpaper\n󰨇 Process Monitor" | wofi --dmenu --cache-file=/dev/null -p "")

case "$choice" in
    " Package Manager")
        sh "$HOME"/.bin/pkgMenu
        ;;
    " Settings")
        sh "$HOME"/.bin/settingsMenu 
        ;;
    "󰋩 Randow Wallpaper")
       sh "$HOME"/.bin/randWpp
        ;;
    "󰨇 Process Monitor")
       kitty --title="floatterm" -e btop
        ;;
    *)
esac
