#!/bin/bash 

choice=$(printf " Back\n󰏕 Install\n󰏕 AUR Install\n󰏔 Uninstall\n󰏓 Purge\n󰚰 Update" | rofi -dmenu -p "")

case "$choice" in
    " Back")
        sh "$HOME"/.bin/mainMenu
        ;;
    "󰏕 Install")
        kitty --title="floatterm" -e sh "$HOME"/.bin/pkgInstall
        ;;
    "󰏕 AUR Install")
        kitty --title="floatterm" -e sh "$HOME"/.bin/pkgInstallAur
        ;;
    "󰏔 Uninstall")
        kitty --title="floatterm" -e sh "$HOME"/.bin/pkgRemove 
        ;;
    "󰏓 Purge")
        kitty --title="floatterm" -e sh "$HOME"/.bin/pkgPurge 
        ;;
    "󰚰 Update")
        kitty --title="floatterm" -e sh "$HOME"/.bin/pkgUpdate
        ;;
    *)
esac
