#!/bin/bash

DIR="$HOME/Screenshots"
mkdir -p "$DIR"
FILE="$DIR/$(date +%Y-%m-%d_%H-%M-%S).png"

if [[ "$1" = "-f" ]]; then
  grim "$FILE"
elif [[ "$1" = "-s" ]]; then
  grim -g "$(slurp -d -b 6c708640 -c d1d7e8ff -w 0)" -t ppm - | satty --filename - 2>/dev/null
  exit
else
  grim -g "$(slurp -d -b 6c708640 -c d1d7e8ff -w 0)" "$FILE"
fi
wl-copy < "$FILE"
