#!/bin/sh 

choice=$(printf " Back\n Config\n Style" | rofi -dmenu -p "")

case "$choice" in
    " Back")
        sh "$HOME"/.bin/settingsMenu
        ;;
    " Config")
        ghostty -e nvim "$HOME"/.config/waybar/config.jsonc
        ;;
    " Style")
        ghostty -e nvim "$HOME"/.config/waybar/style.css
        ;;
    *)
esac
